export const cmsRegistry = {
  homepage: [
    "announcementBar",
    "hero",
    "trustBadges",
    "brandStory",
    "benefits",
    "bodyMetrics",
    "howItWorks",
    "comparison",
    "appPreview",
    "gallery",
    "timeline",
    "reviews",
    "faq",
    "guarantee",
    "newsletter",
    "instagramFeed",
    "relatedProducts",
    "finalCta",
  ],
  commerce: [
    "products",
    "variants",
    "collections",
    "categories",
    "inventory",
    "coupons",
    "upsells",
    "crossSells",
  ],
  settings: [
    "navigation",
    "footer",
    "brandColors",
    "theme",
    "seo",
    "metaData",
    "analytics",
    "pixels",
    "locales",
    "currencies",
    "rtlLtr",
  ],
  admin: [
    "orders",
    "customers",
    "marketing",
    "mediaLibrary",
    "appearance",
    "homepageBuilder",
    "pageBuilder",
    "blog",
    "notifications",
    "users",
    "roles",
    "permissions",
    "auditLogs",
    "activityLogs",
    "backup",
    "security",
  ],
} as const;

export type CmsArea = keyof typeof cmsRegistry;
